### PR TITLE
Fix height and width params, set trainable true

### PR DESCRIPTION
**Pull request by amirbar**
fix Issue #48

### CODE REVIEW

**Comment by futurely** [comment]
What are the results before and after this fix?

**Comment by amirbar** [comment]
The results are bad before and after, but this fix is essential anyway..

**Comment by amirbar** [comment]
@CharlesShang please review

**Comment by amirbar** [comment]
@futurely, I was able to train the RPN network after it (But not the whole pipeline)

These are the RPN results after 190k itr:

image

**Comment by amirbar** [comment]
From my experience these 2 fixes are crucial to train the RPN!!
@CharlesShang Please review ASAP

**Comment by yangJirui** [comment]
Hi amirbar:
I have replaced the height and width with new_height, new_width. But i still can not draw the correct box(final predict) in the image because of the wrong prediction, and my total loss is not decrease after 8K iters. I have changed the learning rate, but it does not work . Just like the graph below:
losses
Have you faced that? And what's your learning rate? @amirbar

**Comment by amirbar** [comment]
Did you set trainable=True within the resnet?

I did both and I commented out every component other than the RPN. I get
decent results from the RPN now

2017-06-07 11:55 GMT+03:00 yangJirui <notifications@github.com>:

**Comment by blitu12345** [comment]
@amirbar  how did you get this result, have you wrote a test file for it or you have taken this RPNs while training of the models.

**Comment by amirbar** [comment]
@blitu12345 just while training the model

**Pull request merged**
