### PR TITLE
Fixed the order of rois in #68

### PR DESCRIPTION
**Pull request by souryuu**
After the following changes I got some improvement on classification results
test_est_80190

1. Set resnet to be trainable and correct the size of image. @amirbar has already fixed this in his recent commit #50.
2. Match the order of rois and crop_rois.
3. Add batch normalization. I changed all the _extra_conv_conv_scope in pyramid_network.py to _extra_conv_arg_scope_with_bn.

Changes in 1 and 2 seem to be critical. I did not compare the version with and without the changes in 3 yet but it made the trained network to produce decent (more colorful?) cropped_rois.

### CODE REVIEW

**Comment by HuangBo-Terraloupe** [comment]
@souryuu 
Hello,
If I understand correctly, we need re-train the network based on your changes,
and we also be able to generate evaluation samples with bounding box and classification results?
please give us more details.
Now we are able to generate bounding box using test_data.py.
But we still do not have classification and segmentation results.

**Comment by souryuu** [comment]
Yes, you need to retrain the network again.
The results shown here are not from test_data.py.
They are the results of bounding box regression and classification during training. 
Removing the comment between line 284-291 in train.py should save the image shown above in output/maskrcnn/est_imgs/

**Comment by realwecan** [comment]
@souryuu I have just tested with your codes, thanks for this really helpful contribution!

It seems to me that using the model trained with your codes, almost all predictions belong to the first class (i.e., `person'). I have trained a model with 50K iteration now, but it seems that predictions are very strongly biased towards the `person' class. Do you observe this in your experiments?

**Comment by souryuu** [comment]
@realwecan Yes, I observed that prediction is biased toward person class.

**Comment by souryuu** [comment]
@realwecan After I look at the results after 600k, the bias is reduced and the network can predict other classes correctly as well. However it is still far from perfect.

**Comment by realwecan** [comment]
@souryuu Thanks for the prompt reply! I really appreciate it!

I will continue to train my model and monitor the outputs then. Another strange problem is that the code will cause out of memory error (produced by CUDA) after running for a while. It seems to be random. Did you notice that, and if yes, do you have any suggestions for a solution?

**Comment by realwecan** [comment]
@souryuu Any chance you could share a trained model with us? I just realized 600k will take a long time with a single GPU.

**Comment by souryuu** [comment]
@realwecan
 I am not sure about the out of memory issue. Changing the number in the following line in train.py back to 0.8 may solve your issue.   
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.95)

Regarding the trained model, I can not upload it due to the restriction of my working environment.

**Comment by HuangBo-Terraloupe** [comment]
@souryuu 
Can you please share weights you trained ?

**Comment by realwecan** [comment]
@souryuu Thanks a lot, I understand. I will train the model myself and see if I could get rid of the class bias problem.

**Comment by realwecan** [comment]
@souryuu Just wanted to check if you could let me know how many iterations you have trained so far; and how do the masks look like? Do they look nice? Just wanted to make sure the current mask prediction process is working well.

**Comment by amirbar** [comment]
Thanks @souryuu I'll try hard to review by end of week

**Pull request merged**
